### ISSUE TITLE
Switch doesn't work

### ISSUE THREAD

**Issue by ghost** [Parou/SVG-Dark-Theme-Switcher#2]
the switch doesn't work even though it works in the demo
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/25064782/41108463-de3e8c6a-6a74-11e8-8582-0b818ca7c871.gif)

**Comment by Parou** [comment]
The switch doesn't work locally because it uses the cookie state to trigger the animation to work site-wide on every instance of the switch. It can't set and read the cookie in a local document.

**Comment by ghost** [comment]
oh right. i forgot that. Nevermind then!

**Comment by Parou** [comment]
I could theoretically make it trigger the animation on click AND when the cookie is set. But I explicitely decided against it since (to me) it makes no sense to have the switch imply that it works, when it actually doesn't. This way the animation is a good implicator that the whole thing works.

**Comment by ghost** [comment]
But the switch not working locally can be annoying when trying to use the switch in your website.
You have to upload/push your website everytime you want to test the switch

**Comment by Parou** [comment]
Yeah... but... see... Once you know that the switch itself works, you don't need to check this everytime. And further work on the part that handles it, needs testing in a non-local environment anyways. Changing the animation trigger wouldn't change anything about the fact that cookies don't work that way. It just doesn't work on the file:/// protocol. That's normal.

**Comment by Parou** [comment]
Btw: I recommend you to run a lightweight webserver like nginx or lighttpd on your PC for proper local testing of none-purely static websites without publishing them. Even JavaScript usually doesn't always work properly if opened via file:///.
