### ISSUE TITLE
Huge blank space

### ISSUE THREAD

**Issue by ghost** [Parou/SVG-Dark-Theme-Switcher#3]
There is a huge blank space before and after the switch. 
I have no idea why i and have no experience with html,css or javascript.
https://github.com/Hampusm/hampusm.github.io
![imsad](https://user-images.githubusercontent.com/25064782/41119407-0578de3e-6a93-11e8-9abf-32ab717514e6.png)

**Comment by Parou** [comment]
Ehm... that's simple. Your .content div is a flex element that has the width and height of the complete viewport, while it isn't set to the far left, resulting in still centering the switch in your .content, while the ,content is completely off.

**Comment by Parou** [comment]
Your .content has 100vw as width, which means 100% of the viewport width. But your .content is inside another element #main_content, which on the other hand hasn't even near that size and is centered on the page. That causes the .content being completely off.

**Comment by Parou** [comment]
![switcher](https://user-images.githubusercontent.com/28531401/41122599-5e372888-6a9c-11e8-8637-383e24e04a66.PNG)

**Comment by ghost** [comment]
Thank you for answering and i am sorry for asking so dumb questions

**Comment by Parou** [comment]
It's not dumb. It's perfectly reasonable when you don't have much experience with it.
